version: '3'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
            - '8081:3000'
        links:
            - mongo
        depends_on:
            - mongo
        
    mongo:
        container_name: mongo-mymdb
        image: mongo
        ports:
            - '27018:27017'
        volumes:
            - mymdb_data:/var/lib/mongodb/data
        

volumes:
    mymdb_data:

